# Generated by Django 5.2.7 on 2025-11-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('electronic', 'Electronic'), ('hip-hop', 'Hip-Hop'), ('lo-fi', 'Lo-Fi'), ('ambient', 'Ambient'), ('house', 'House'), ('techno', 'Techno'), ('drum-and-bass', 'Drum and Bass'), ('jazz', 'Jazz'), ('funk', 'Funk'), ('soul', 'Soul'), ('pop', 'Pop'), ('rock', 'Rock'), ('indie', 'Indie'), ('experimental', 'Experimental'), ('other', 'Other')], default='other', max_length=50)),
                ('bpm', models.IntegerField(default=120, help_text='Tempo в BPM')),
                ('audio_file', models.FileField(upload_to='loops/')),
                ('likes', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Loop',
                'verbose_name_plural': 'Loops',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
