# Generated by Django 5.2.7 on 2025-11-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_sample'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Sample', 'verbose_name_plural': 'Samples'},
        ),
        migrations.AddField(
            model_name='sample',
            name='genre',
            field=models.CharField(choices=[('electronic', 'Electronic'), ('hip-hop', 'Hip-Hop'), ('lo-fi', 'Lo-Fi'), ('ambient', 'Ambient'), ('house', 'House'), ('techno', 'Techno'), ('drum-and-bass', 'Drum and Bass'), ('jazz', 'Jazz'), ('funk', 'Funk'), ('soul', 'Soul'), ('pop', 'Pop'), ('rock', 'Rock'), ('indie', 'Indie'), ('experimental', 'Experimental'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
