# Generated by Django 5.2.8 on 2025-12-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_loop_downloads_sample_downloads_alter_loop_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loop',
            name='keywords',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
