# Generated by Django 5.2.8 on 2025-12-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_sample_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loop',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='likes',
        ),
    ]

