# Generated by Django 5.2.8 on 2025-12-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0007_remove_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loop',
            name='bpm',
            field=models.IntegerField(default=120, help_text='Tempo in BPM'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(choices=[('bass', 'Bass'), ('hi_hat', 'Hi Hat'), ('clap', 'Clap'), ('kick', 'Kick'), ('snare', 'Snare'), ('tom', 'Tom'), ('perc', 'Perc'), ('other', 'Other')], max_length=20),
        ),
    ]
