# Generated by Django 5.2.8 on 2026-02-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0008_alter_loop_bpm_alter_sample_sample_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loop',
            name='waveform_duration',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loop',
            name='waveform_peaks',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loop',
            name='waveform_source_file',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='sample',
            name='waveform_duration',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='waveform_peaks',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='waveform_source_file',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
