# Generated by Django 5.2.8 on 2026-02-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0009_loop_waveform_duration_loop_waveform_peaks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loop',
            name='bpm_detection_confidence',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loop',
            name='bpm_last_detected_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='loop',
            name='bpm_needs_review',
            field=models.BooleanField(default=False),
        ),
    ]
