# Generated by Django 5.2.8 on 2026-03-16 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drumkits', '0002_drumkit_genre'),
        ('uploader', '0011_loop_preview_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrumKitComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drumkit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='drumkits.drumkit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drumkit_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoopComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='uploader.loop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loop_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrumKitLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drumkit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='drumkits.drumkit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drumkit_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'drumkit'), name='social_unique_drumkit_like')],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_relations', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('follower', 'author'), name='social_unique_follow'), models.CheckConstraint(condition=models.Q(('follower', models.F('author')), _negated=True), name='social_prevent_self_follow')],
            },
        ),
        migrations.CreateModel(
            name='LoopLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='uploader.loop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loop_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'loop'), name='social_unique_loop_like')],
            },
        ),
        migrations.CreateModel(
            name='SampleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='uploader.sample')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'sample'), name='social_unique_sample_like')],
            },
        ),
    ]
