# Generated by Django 5.2.7 on 2025-11-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sample_type', models.CharField(choices=[('bass', 'Басс'), ('hi_hat', 'Hi Hat'), ('clap', 'Clap'), ('kick', 'Kick'), ('snare', 'Snare'), ('tom', 'Tom'), ('perc', 'Перкуссия'), ('other', 'Другое')], max_length=20)),
                ('audio_file', models.FileField(upload_to='samples/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
