# Generated by Django 5.2.8 on 2025-12-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_alter_sample_options_sample_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='loop',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sample',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loop',
            name='genre',
            field=models.CharField(choices=[('electronic', 'Electronic'), ('hip-hop', 'Hip-Hop'), ('hoodtrap', 'Hoodtrap'), ('drill', 'Drill'), ('voice', 'Voice'), ('ambient', 'Ambient'), ('house', 'House'), ('techno', 'Techno'), ('drum-and-bass', 'Drum and Bass'), ('pop', 'Pop'), ('rock', 'Rock'), ('experimental', 'Experimental'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='genre',
            field=models.CharField(choices=[('electronic', 'Electronic'), ('hip-hop', 'Hip-Hop'), ('hoodtrap', 'Hoodtrap'), ('drill', 'Drill'), ('voice', 'Voice'), ('ambient', 'Ambient'), ('house', 'House'), ('techno', 'Techno'), ('drum-and-bass', 'Drum and Bass'), ('pop', 'Pop'), ('rock', 'Rock'), ('experimental', 'Experimental'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_type',
            field=models.CharField(choices=[('bass', 'Bass'), ('hi_hat', 'Hi Hat'), ('clap', 'Clap'), ('kick', 'Kick'), ('snare', 'Snare'), ('tom', 'Tom'), ('perc', 'Perc'), ('other', 'Другое')], max_length=20),
        ),
    ]
