# Generated by Django 5.2.8 on 2025-12-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_loop_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]

