# Generated by Django 5.2.8 on 2026-02-28 00:00

import apps.drumkits.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='DrumKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, default='', max_length=100)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=apps.drumkits.models.drumkit_cover_upload_to)),
                ('archive_file', models.FileField(blank=True, null=True, upload_to=apps.drumkits.models.drumkit_archive_upload_to)),
                ('is_public', models.BooleanField(default=True)),
                ('downloads', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Drum kit',
                'verbose_name_plural': 'Drum kits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrumKitFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relative_path', models.CharField(max_length=500)),
                ('folder_path', models.CharField(blank=True, default='', max_length=500)),
                ('audio_file', models.FileField(upload_to=apps.drumkits.models.drumkit_audio_upload_to)),
                ('duration', models.FloatField(blank=True, default=None, null=True)),
                ('waveform_peaks', models.JSONField(blank=True, default=None, null=True)),
                ('waveform_duration', models.FloatField(blank=True, default=None, null=True)),
                ('waveform_source_file', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kit', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='files', to='drumkits.drumkit')),
            ],
            options={
                'verbose_name': 'Drum kit file',
                'verbose_name_plural': 'Drum kit files',
                'ordering': ['relative_path'],
                'constraints': [models.UniqueConstraint(fields=('kit', 'relative_path'), name='drumkit_unique_relative_path_per_kit')],
            },
        ),
    ]
