# Generated by Django 5.2.8 on 2026-03-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drumkits', '0002_drumkit_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drumkit',
            name='genre',
            field=models.CharField(choices=[('hip-hop', 'Hip-Hop'), ('trap', 'Trap'), ('hoodtrap', 'Hoodtrap'), ('drill', 'Drill'), ('detroit', 'Detroit'), ('new-jazz', 'New jazz'), ('glo', 'Glo'), ('opium', 'Opium'), ('plug', 'Plug'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
