# Generated by Django 5.2.7 on 2025-11-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loop',
        ),
    ]
