# Generated by Django 5.2.8 on 2026-03-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drumkits', '0003_alter_drumkit_genre'),
        ('uploader', '0013_alter_loop_genre_alter_sample_genre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_alter_profile_avatar_alter_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now=True)),
                ('drumkit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downloaded_by_users', to='drumkits.drumkit')),
                ('loop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downloaded_by_users', to='uploader.loop')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downloaded_by_users', to='uploader.sample')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads_library', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-downloaded_at'],
                'indexes': [
                    models.Index(fields=['user', '-downloaded_at'], name='acct_udl_user_dt_idx'),
                ],
                'constraints': [
                    models.CheckConstraint(
                        condition=(
                            (models.Q(drumkit__isnull=True, loop__isnull=False, sample__isnull=True))
                            | (models.Q(drumkit__isnull=True, loop__isnull=True, sample__isnull=False))
                            | (models.Q(drumkit__isnull=False, loop__isnull=True, sample__isnull=True))
                        ),
                        name='acct_udl_one_target_chk',
                    ),
                    models.UniqueConstraint(condition=models.Q(loop__isnull=False), fields=('user', 'loop'), name='acct_udl_user_loop_uq'),
                    models.UniqueConstraint(condition=models.Q(sample__isnull=False), fields=('user', 'sample'), name='acct_udl_user_sample_uq'),
                    models.UniqueConstraint(condition=models.Q(drumkit__isnull=False), fields=('user', 'drumkit'), name='acct_udl_user_drumkit_uq'),
                ],
            },
        ),
    ]
